language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
env:
  - SBT_TARGET=transactor
  - SBT_TARGET=l_space
  - SBT_TARGET=translation_engine
  - SBT_TARGET=protocol
  - SBT_TARGET=rpc
script:
  - sbt $SBT_TARGET/test
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
notifications:
  slack: mediachain:gzFe4w4HwIlNnxaHy1vAKW3q
  on_success: change
  on_failure: change
matrix:
  allow_failures:
    - env: SBT_TARGET=transactor
