---

- name: copy init.d script to system
  template: src={{role_path}}/templates/ipfs.init.j2 dest=/etc/init.d/ipfs owner=root group=root mode=0755

- name: make ipfs service start on boot
  command: creates="/etc/rc0.d/*ipfs" /usr/sbin/update-rc.d -f ipfs defaults
