- name: "Create dynamo directory"
  file:
      path="/opt/dynamodb"
      state="directory"

- name: "Download the DynamoDB local jar"
  get_url:
    url="http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_{{dynamodb_version}}.tar.gz"
    sha256sum="{{dynamodb_sha}}"
    dest=/opt/dynamodb/dynamodb_local_{{dynamodb_version}}.tar.gz
  notify:
   - Restart DynamoDB
  register: dynamodb_download

- name: "Install DynamoDB in /opt/dynamodb"
  shell: |
    tar -zxf ./dynamodb_local_{{ dynamodb_version }}.tar.gz
    chdir="/opt/dynamodb"

  when: dynamodb_download.changed

- name: "Drop an init.d file for DynamoDB"
  template: >
    src=dynamodb.init.sh.j2
    dest=/etc/init.d/dynamodb
    mode=0700
    owner=root
    group=root
  notify:
    - Restart DynamoDB

- name: "Make sure DynamoDB local development is running"
  service: >
    name=dynamodb
    state=running
    enabled=yes
    runlevel=5
    pattern="DynamoDBLocal.jar"
