# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # Use a box compatible with both virtualbox and vmware_fusion providers
  config.vm.box = "phusion/ubuntu-14.04-amd64"

  # Since the Vagrantfile is in a subdirectory of the project root,
  # share the parent directory at /mediachain
  config.vm.synced_folder "../", "/mediachain"

  # If the python client is a sibling of the project root, share it
  # at /mediachain-client
  if File.exist? "../../mediachain-client"
    config.vm.synced_folder "../../mediachain-client", "/mediachain-client"
  end

  if ENV["MC_VAGRANT_IP"]
    config.vm.network "private_network", ip: ENV["MC_VAGRANT_IP"]
  else
    config.vm.network "private_network", type: "dhcp" 
  end

  # Set ram, etc for vm providers
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provider "vmware_fusion" do |vm|
    vm.memory = "2048"
  end

  # Set hostname for vm
  config.vm.define "transactor"

  # Ansible config
  config.vm.provision :ansible do |ansible|
    ansible.limit = "transactors"
    ansible.playbook = "playbooks/dev.yml"
    ansible.groups = { "transactors" => ["transactor"] }
  end
end
